services:
  - type: web
    name: minsouah-immobilier-cy30
    runtime: static
    buildCommand: npm install && NODE_OPTIONS=--max-old-space-size=1536 npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
