/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#353026',
        'on-secondary': '#ffffff',
        'outline-variant': '#d2c5ae',
        'outline': '#817662',
        'on-error-container': '#93000a',
        'surface-container-low': '#fdf2e3',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#5a4300',
        'secondary-fixed': '#ebe0dd',
        'primary-fixed': '#ffdf9b',
        'primary-container': '#e5b228',
        'inverse-primary': '#f4bf36',
        'on-surface': '#1f1b12',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#5e4600',
        'secondary-container': '#ebe0dd',
        'inverse-on-surface': '#faefe0',
        'surface-variant': '#ebe1d2',
        'primary': '#785a00',
        'on-tertiary-fixed-variant': '#004b74',
        'on-secondary-fixed-variant': '#4c4543',
        'surface': '#fff8f2',
        'error': '#ba1a1a',
        'tertiary-container': '#75c0ff',
        'background': '#fff8f2',
        'on-secondary-fixed': '#1f1a19',
        'primary-fixed-dim': '#f4bf36',
        'on-error': '#ffffff',
        'surface-dim': '#e3d9ca',
        'surface-container': '#f7edde',
        'surface-tint': '#785a00',
        'tertiary-fixed-dim': '#94ccff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#001d32',
        'on-secondary-container': '#6a6360',
        'on-background': '#1f1b12',
        'tertiary': '#006399',
        'surface-container-high': '#f1e7d8',
        'on-tertiary-container': '#004e79',
        'on-primary-fixed': '#251a00',
        'secondary-fixed-dim': '#cec4c1',
        'on-surface-variant': '#4f4634',
        'surface-bright': '#fff8f2',
        'secondary': '#645d5a',
        'tertiary-fixed': '#cde5ff',
        'surface-container-highest': '#ebe1d2',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', fontWeight: '700' }],
        h1: ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0px 4px 20px rgba(62,56,54,0.05)',
        modal: '0px 10px 30px rgba(62,56,54,0.12)',
        topbar: '0px 4px 20px rgba(62,56,54,0.05)',
      },
    },
  },
  plugins: [],
};
